### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by vdemichev** [lazear/sage#11]
Hi Michael,

Many thanks for the fantastic search engine, and congrats!
Do you think you could share some details on how to install and use it? Is it for Linux or Windows? Just unfamiliar with Rust, not sure how to start using Sage :)

Best,
Vadim

**Comment by lazear** [comment]
Hi Vadim,

Apparently I only included instructions in the blog post, and not the README (that's embarrassing...) - hopefully the instructions I have provided are clear enough for you to follow. Please let me know if you run into trouble!

Good reminder for me to look into supplying pre-built binaries as well.

**Comment by wfondrie** [comment]
@lazear - would you want a PR for a GitHub action to build sage on new releases? If so, I'm happy to contribute.

**Comment by lazear** [comment]
@wfondrie that would be fantastic! Not sure if you have done Rust CI builds before - one thing to be aware of (for linux builds) is the glibc version. Rust statically links everything *except* glibc, and this can cause binaries to be incompatible across linux distros if, for instance, the CI container is using glibc 2.31 (as I believe Ubuntu 20.04 does), but the user is running a stock EC2 amazon linux instance (running glibc 2.26)

Rust is moving to a requirement for glibc >= 2.17 by end of September, so if possible it would be ideal to find some container with a glibc version as close as possible (at least 2.26) to maximize who can use the binaries.

See:
- https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html
- https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html

**Comment by vdemichev** [comment]
Great, thank you!
