### ISSUE TITLE
Sage TSV output notes

### ISSUE THREAD

**Issue by douweschulte** [lazear/sage#127]
* The `longest_y_pct` column output is seemingly as a fraction.
```plain
peptide_len longest_y longest_y_pct
          9         2   0.22222222
         13        10   0.7692308
          9         2   0.22222222
         17         3   0.1764706
         17         3   0.1764706
          9         2   0.22222222
          9         2   0.22222222
         17         5   0.29411766
         17         5   0.29411766
```
_Personally I do not see the use of this column as any place where you would do analysis (eg excel at the very least) can recreate this column and this is a division which might not be fully mathematically correct in floating point so recalculating it might be a better way anyways, but that is besides the point (for a bug fix and patch release)._

* I assume the `rt` column is in minutes, but having this explicit in the documentation would be nice.
* The documentation mentions a column `ms1_intensity` which is not present in the actual file.
* The columns `ion_mobility`, `predicted_mobility`, and `delta_mobility` are not described in the documentation.

**Comment by lazear** [comment]
Thanks, I have updated the documentation!

Many of the columns are not useful for downstream analysis in Excel, and are present to enable re-scoring with other tools (percolator, ms2rescore) etc.

I'm not particularly concerned about f32 representation of fractions.

**Comment by douweschulte** [comment]
Perfect! Thanks for getting back so fast!

**Comment by douweschulte** [comment]
Tiny nitpick there is a typo in the new description for `delta_mobility`: predicteed.

**Comment by lazear** [comment]
Thanks! Got it fixed
