### ISSUE TITLE
[Feature Request] Sage output as a pepXML file

### ISSUE THREAD

**Issue by sciordia** [lazear/sage#130]
I would like to import the results obtained with Sage into the Trans Proteomic Pipeline (TPP). I want to create a spectral library from the results but I would need the Sage output as a pepXML file. Would it be possible to add this export option in Sage, please?.

Thank you very much.

Best regards,
Sergio

**Comment by lazear** [comment]
Hi Sergio,

I'm not really interested in supporting any additional XML based formats (it's 2024) directly in Sage. It should be possible to write an adaptor in python/R that takes the existing output files and maps them to whatever format you need!

**Comment by sciordia** [comment]
Thank you very much for your answer @lazear, maybe you are right but pepXML is still a very common format and almost all programs work with it. It is the usual format for TPP, mokapot, etc. 
In any case, as you say, I will try to convert the TXT output file from Sage in R to pepXML, I hope to get it.

Thanks again for your time.

Best regards,
Sergio

**Comment by lazear** [comment]
I'm happy to add a link to your tool in the Sage README if you put it on Github!

**Comment by lazear** [comment]
Thanks - I can add a link to it. There is an old branch in this codebase for producing mzIdentML (could probably be revived), but it's a quite tricky format and can take a long time/lot of space to generate... and I also found issues in that some consumers of mzIdentML actually reject the standards-compliant version (tested against the reference tool) that I produced.
