### ISSUE TITLE
discrepancies in results between penultimate and latest version

### ISSUE THREAD

**Issue by animesh** [lazear/sage#148]
First i must commend on full reproducibility of results within same version 👌which unfortunately i cannot claim yet for my belowed MaxQuant 🤪 below is an example where 5 HeLa samples run twice 

![image](https://github.com/user-attachments/assets/be5bc45e-2ee6-4abd-a808-b1c65594f2e9)

using version 0.14.7 via the `docker run --rm -it -v /home/data:/data ghcr.io/lazear/sage:v0.14.7` but when i compare with results using the container i created using the latest/0.15.0-alpha `docker run --rm -it -v /home/data:/data animesh1977/sage /data/sage.json -f /data/human_crap.fasta -o /data /data/240624_200ngHelaQC_DDAlong_Slot1-54_1_7830.mzML /data/240624_200ngHelaQC_DDAlong_Slot1-54_1_7831.mzML /data/240624_200ngHelaQC_DDAlong_Slot1-54_1_7832.mzML /data/240605_200ngHelaQC_DDAlong_Slot1-54_1_7643.mzML /data/240605_200ngHelaQC_DDAlong_Slot1-54_1_7641.mzML` i see few difference in overlap
![image](https://github.com/user-attachments/assets/a582b1df-5e07-4317-986a-736b7784a477)
and a lot in terms of quantification, below scatter shows spearman-correlation in blue
![image](https://github.com/user-attachments/assets/6b56b8d5-1df0-4965-a95d-e2b3d293a3f4)
where difference seems to be mostly in the median-range, is this something to be expected? 

I must mention that to keep the same parameters [sage.json](https://github.com/user-attachments/files/16426538/sage.json), i had to remove the PTMs, could that cause this picture?

**Comment by lazear** [comment]
You shouldn't have to remove PTMs... Just specify them as a list. Doing otherwise has caused a warning to pop up for the last several versions of Sage.

```json
"variable_mods": {
   "M": [15.994]
}
```

**Comment by lazear** [comment]
Overall quant across all high-quality precursors (q_value < 0.01) is pretty close (pearson's R=0.98) across versions. Ideally, it would be identical, but that isn't a guarantee I can make - especially since no changes to the quantification algorithm have been made.

![cmp](https://github.com/user-attachments/assets/54cd20e9-2073-400a-9a82-6cde9aee36b8)
