### ISSUE TITLE
[Docs] Fragment masses are present

### ISSUE THREAD

**Issue by jspaezp** [lazear/sage#157]
The parameter was removed here:
https://github.com/lazear/sage/commit/d1280a73152bf74e22d1c5a9dec3ec8231bd5074

But the documentation still shows it as existing:
- https://sage-docs.vercel.app/docs/configuration
- https://github.com/lazear/sage/blob/master/DOCS.md
- ... benchmark configs ... where you might want to leave it ... or not...

LMK if you want PR for the cleanup (I have no idea where the source for the vercel site is ...)

**Comment by lazear** [comment]
A PR would be great - docs are here: https://github.com/lazear/sage-docs
