### ISSUE TITLE
Amino acid substitutions as variable modifications

### ISSUE THREAD

**Issue by tommasomari** [lazear/sage#163]
I was wondering if there is a way in Sage to set a variable modification the substitution of a specific amino acid to another one. While certain AA substitutions can be achieved by giving the mass difference, if the substitution were to happen on an AA used for enzyme digestion or that can have a variable modification itself, this would have a big impact on the database for search.

**Comment by lazear** [comment]
Can you provide some more details?

Are you interested in just a single peptide? Single AA -> AA substitution, etc? Is it an AA used for enzyme digestion?

**Comment by lazear** [comment]
Gotcha. In this case, if you expect the modification is prevalent, you could try  creating a version of your fasta database where you have generated all permutations of protein sequences with R->C mutations (Sage will handle removing duplicated peptides, and it won't affect protein assignment). If you're only interested in a handful of proteins, it's even simpler.
Alternatively, use the R - C mass difference as a variable mod on R and crank up the number of missed cleavages.

**Comment by tommasomari** [comment]
Thanks a lot for the tip, I’ll try all three options and evaluate / compare the outcome.
