### ISSUE TITLE
Binaries built at release with platform names

### ISSUE THREAD

**Issue by Elendol** [lazear/sage#23]
Hi,

Currently the binaries from the release page have the name of the platform they were compiled for  (`Linux.64-bit`) instead of something like `sage`.

**Comment by lazear** [comment]
How about something like `sage-macos-aarch64`, `sage-linux-amd64`, etc?

**Comment by lazear** [comment]
You should be able to modify these two files, if you're willing to take a stab:

https://github.com/lazear/sage/blob/master/.github/workflows/build.yml
https://github.com/lazear/sage/blob/master/.github/workflows/upload_artifacts/action.yml

**Comment by Elendol** [comment]
my PR should deal with that. Hope that helps
