### ISSUE TITLE
Enable integration with PeptideShaker

### ISSUE THREAD

**Issue by lazear** [lazear/sage#27]
- [x] Rename `discriminant_score` to `sage_discriminant_score`
- [x] Add a column indicating the rank of a PSM for a given spectrum
- [x] Investigate the performance impact of tracking spectrum ID along with/in lieu of scan number

Reference conversation at: https://github.com/compomics/searchgui/issues/334

**Comment by lazear** [comment]
Minor, if any, increase in memory usage for tracking spectrum ID.

- Note that we aren't currently doing any lookups using spectrum ID/scan number anyway right now, since TMT MS3-SPS quant needs to be re-worked. That's primarily where any slowdown would occur, and I think it's probably still an acceptable perf hit

**Comment by kostrouc** [comment]
Does this mean that the "scannr" column corresponds to an index of the scan within a provided mzML file? It does not represent the actual spectrum ID?

**Comment by lazear** [comment]
@kostrouc, the scannr column corresponds to the spectrum ID from the mzML file - previously the integer value ("scan=(\d+)") was extracted, but not all instruments/vendors reported spectrum IDs in the same format. This was changed a while ago (https://github.com/lazear/sage/commit/3ed80124313688c8ecf8380ca9a87809e0e44e83)

In the example below, the scan number is 1-indexed.

`<spectrum index="0" id="controllerType=0 controllerNumber=1 scan=1" defaultArrayLength="1400">`

So "scannr" would be "controllerType=0 controllerNumber=1 scan=1".
