### ISSUE TITLE
How to deal with DIA data?

### ISSUE THREAD

**Issue by wangshisheng** [lazear/sage#35]
Hi Lazear,

Great software Sage is. I am wondering whether Sage could deal with DIA data? Is there some detailed introduction about that?
Many thanks.

Bests,
Shisheng

**Comment by lazear** [comment]
Hi Shisheng,

I don't have any plans to support DIA data... yet. I was playing around with some wide-window acquisition data and Sage seems to work pretty well - and I think that would translate to DIA.
If there is more interest it's something I would be willing to look into down the line

Best,
Mike
