### ISSUE TITLE
Support additional enzymes

### ISSUE THREAD

**Issue by lazear** [lazear/sage#37]
Add support for:

- [x] Enzymatic cleavage N-terminal to sites
- [x] Non-specific digest
- [x] No digest

**Comment by jonasscheid** [comment]
Hi! Thanks for this great tool and the tremendous work you put in here 🙏 
I want to try out non-specific digest and was wondering how to provide this in the config file?
Providing `"cleave_at": ""` and/or `"restrict":""` does not seem to work.

**Comment by lazear** [comment]
Hi @jonasscheid, can you clarify what you mean by did not work - was there an error, or no results, etc?

**Comment by jonasscheid** [comment]
Sure. I provided the following config:

> {
  "database": {
      "bucket_size": 16384,
      "fragment_min_mz": 150.0,
      "fragment_max_mz": 1500.0,
      "enzyme": {
        "missed_cleavages": 0,
        "min_len": 8,
        "max_len": 12,
        "cleave_at": ""
      },
      "static_mods": {
        "M": 15.9949
      },
      "decoy_tag": "rev_",
      "generate_decoys": true,
      "fasta": "UP000005640_9606_decoy.fasta"
  },
  "deisotope": true,
  "chimera": false,
  "max_fragment_charge": 1,
  "report_psms": 1,
  "precursor_tol": {
      "ppm": [
          -50,
          50
      ]
  },
  "fragment_tol": {
      "ppm": [
          -10,
          10
      ]
  },
  "isotope_errors": [
      -1,
      3
  ],
  "mzml_paths": [
      "path/to/file.mzML"
  ]
}

And got:

> sage config_test.json
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> regex parse error:
>    []
>    ^^
>error: unclosed character class
>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> )', crates/sage/src/enzyme.rs:106:57
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Aborted (core dumped)

**Comment by lazear** [comment]
Are you using the most recent release build? The recent commits merging in support for non-enzymatic digest hasn't been "officially" released yet! Your config file looks fine otherwise, but I would caution that - based on my testing - you will need a lot of RAM if using a human-sized fasta file (> 64GB likely).

I will push a release out momentarily.

**Comment by lazear** [comment]
@jonasscheid New release binaries are building now (should be done several minutes after this is posted) - please try it out & report back!

**Comment by jonasscheid** [comment]
Ah makes sense, I had the 0.8.1 release from bioconda. I'm trying out the new release right now! I should have enough RAM, lets see

**Comment by jonasscheid** [comment]
Ok, so I managed to run the new release. I ran a local mzML with your test fasta, since the human proteome was just to big. Somehow 256GB RAM was not enough and the job was killed.
But besides that I had a quick look over the output and it looks good 👍 

A quick follow-up question. What would I need to specify for no digest?
Thanks again for the quick responses!

**Comment by lazear** [comment]
Hmm.. interesting - I will see if I can do some tweaks. I was able to successfully run 9-11 peptides on the ProteomeTools TMT-labelled HLA dataset in 64 GB, but also had 9-12 killed. I think there is probably a more intelligent way to create the fragment index for non-specific digests (given a significant amount of shared ions).

For no digest, use the following:
```
"enzyme": {
   "cleave_at": "$",
   "min_len": 0,
   "max_len": 1000
}
```

Note that min_len and max_len still apply, so set them to reasonable values for your pre-digested database.
