### ISSUE TITLE
Version cloned is different from most recent release (v0.8.0)

### ISSUE THREAD

**Issue by k-p4** [lazear/sage#43]
Hi there,

Very cool project and exited to test it out. 

I simply used git clone to clone and build the repo on Windows 11. When I check the version with --version it says v0.7.1.
Was wondering if I was doing something wrong or should be downloading and building from the 0.8.0 zips?

Thanks!

**Comment by lazear** [comment]
@k-p4 you aren't doing anything wrong - right now the version has to be manually updated in the codebase, and it looks like I forgot to do that for the 0.8.0 release 🙃.
