### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by mknierman** [lazear/sage#44]
How do you check the hits?  A visual display of the spectra and ion assignments is very useful.  Did you use something in development?  I see a high number of chimeric spectra returned. I would like to look at these spectra assignments to think about the appropriate scoring thresholds.

**Comment by lazear** [comment]
You can use PeptideShaker to visualize Sage search results (https://github.com/compomics/searchgui/issues/334 - find the links for downloads in this thread, or direct link to https://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/2.2.18-beta/PeptideShaker-2.2.18-beta.zip). I have also made some custom python scripts for visualizing search results as well. If you want to put in the effort to do something more advanced, I have python bindings for Sage (that enable interactivity with the search engine) on Github as well: https://github.com/lazear/sage-pyo3
