### ISSUE TITLE
Why is deisotoping optional?

### ISSUE THREAD

**Issue by Maithy15** [lazear/sage#49]
Dear Michael,

I was going through the example config file and saw that deisotoping is set to false. I thought deisotoping is essential to accurately quantify the peptides. Is there a reason to switch it off?

Thanks
Maithy

**Comment by lazear** [comment]
Why shouldn't it be optional? My philosophy is that we should enable the broadest configuration surface area, when reasonable, to enable workflows that other people may have, even if it's of no immediate use.

In the case of MS2 deisotoping, there are several cases where you might want to turn it off: low-res MS2 (e.g. typical TMT-MS3 workflows), TMT-MS2. I can assure you that there is no issue with identifying peptides when deisotoping is turned off.

You mentioned quantifying peptides, so perhaps you are not thinking of what I have described above -  I should clarify that Sage performs deisotoping only on MS2 spectra. MS1 spectra are left in their deisotoped state, and isotopic envelopes are extracted if LFQ is turned on.
