### ISSUE TITLE
Output directory

### ISSUE THREAD

**Issue by maxochondria** [lazear/sage#51]
How do you specify the output directory in the .json file? I defined the path as shown below but it seems that the results are not saved in the directory I specified and I cannot locate them. Is there a default path where I could retrieve them?

`"output_paths": [
    "/share/mlevasseur/bruker/scp/processed/sage/20230314/"
	]  `

**Comment by lazear** [comment]
Huh, this isn't in the example config file! My bad!

Use the "output_directory" option in the JSON file, or alternatively, you can specify the output directory as a CLI argument:

```jsonc
{
   ...
   "output_directory": "/path/to/data" or "s3://bucket/prefix"
}
```

or

`./sage config.json -o /path/to/data`
