### ISSUE TITLE
Decoy hits have label -1?

### ISSUE THREAD

**Issue by lgatto** [lazear/sage#58]
Not sure where to find the documentation about the sage.result.tsv file, but could you confirm whether the label variable corresponds to decay (-1) and forward (1) hits. 

Thank you!

**Comment by lazear** [comment]
That is correct! This is how target/decoys are specified for percolator. Decoy peptides should also have proteins with decoy tags as part of the identifier as well

Another vote for better docs 😉

**Comment by lgatto** [comment]
Thank you!
