### ISSUE TITLE
Option to search for optional modifications

### ISSUE THREAD

**Issue by MKoesters** [lazear/sage#6]
Hi,

First of all, thanks for implementing this algorithm and making it open source!
I'm aware that this tool is not finished (at least from what I understood from the blog post) and that not all features are implemented yet.
I tried the tool and it looks very promising, however I was not able to find an option to specify optional modifications.
Is this something you are working on / something which will be implemented in the future, or am I just missing on how to do that?

Best,
Manuel

**Comment by lazear** [comment]
Hi Manuel - 

It's great to hear that you tried out Sage! Variable modifications are definitely on the to-do list - I want to test out a couple different approaches and see what works out the best.

Also a great reminder for me to add some documentation on the parameters!

**Comment by lazear** [comment]
Hi @MKoesters,

I have merged in variable modifications (along with a handful of other features), let me know if you give it a try/have any issues!

The format for configuration file has slightly changed, see below for an example of specifying variable modifications
```jsonc
{
  "database": {
    "static_mods": {        // Optional[Dict[char, float]] {default={}}, static modifications
      "^": 304.207,         // Apply static modification to N-terminus
      "K": 304.207,         // Apply static modification to lysine
      "C": 57.0215          // Apply static modification to cysteine
    },
    "variable_mods": {      // Optional[Dict[char, float]] {default={}}, variable modifications
      "M": 15.9949          // Variable mods are applied *before* static mods
    },
  }
}
```

**Comment by MKoesters** [comment]
Hi, 

thanks for the update.
I hope I'll have time to test it this week.
I'll let you if I find any issues
