### ISSUE TITLE
Feature request -- add sage version to returned config 

### ISSUE THREAD

**Issue by lgatto** [lazear/sage#61]
I really like how, as part of the output, sage also returns the config file - that's a great feature for reproducibility and tracking what was really run. 

It would be even more useful if the version that was used added. This would allow to exactly repeat a previous run. 

Thank you for considering!

**Comment by lazear** [comment]
Totally agree - would be very useful for testing across versions of sage as well (throw a warning, or try to convert configuration schemas). The results.json file is also usable as an input file!
