### ISSUE TITLE
Support modification of amino acids at peptide or protein termini

### ISSUE THREAD

**Issue by mvaudel** [lazear/sage#63]
Hi,

Thanks for leading this exciting project. Some common modifications target amino acids at peptide or protein termini.
Examples:
https://www.thegpm.org/TANDEM/api/pqp.html
https://www.thegpm.org/TANDEM/api/pqa.html

Last time I checked, this was not supported. It would be great to have it implemented - or some pointers on how we can help with this :-)

Many thanks,

Marc

**Comment by lazear** [comment]
Marc,

I've added support for modifications of amino acids at peptide/protein termini:
```json
"variable_mods": {
    "M": [15.9949],
    "^Q": -17.026549,
    "^E": -18.010565,
    "[": 42.010565
}
```

You can also now specify multiple modifications for a single amino acid/terminus. SearchGUI/PeptideShaker came in handy while developing this - super easy to run X!Tandem/Comet and drop in the Sage results to compare 😃.
