### ISSUE TITLE
Supports for cross-linking searching?

### ISSUE THREAD

**Issue by Dead-fisher** [lazear/sage#79]
Hi Michael,

Thanks for this excellent project!

I have a specific problem and would like to know whether I can achieve it by modifying sage here.

I have a protein where many residues are randomly labeled by a known peptide. The linker is known. I have the LC-MS/MS data of this molecule (Trypsin degist). Now I want to find which residues of the protein are labeled by the peptide, i.e. to find the label positions. 

So in general, it's more like a cross-linking searching task, but currently I haven't got an idea how to do it in sage. 

Since Sage is the only project I can find which is totally open-source and friendly for coders, do you have idea when to support the crosslinking searching or can you give me some hints if I modify sage to my projects by myself?

Thanks in advance!

**Comment by lazear** [comment]
Hi Yanze

Unfortunately, I'm not very familiar with crosslinking searches or software. [Kojak](https://github.com/mhoopmann/kojak) is an open-source project for performing XL searches - maybe worth giving it a shot?

I think it should be possible to do this in Sage - Based on [this paper](https://link.springer.com/content/pdf/10.1007/s13361-011-0261-2.pdf), it seems somewhat analogous to a open-search/mass-offset search + localization, with diagnostic ions from the known peptide (but again, I am not familiar with algorithms for searching XL data). This might not give you results as high quality as using a tool specifically designed for XL though.
