### ISSUE TITLE
Documentation/specification of precursor charge range

### ISSUE THREAD

**Issue by jpfeuffer** [lazear/sage#85]
Hi @lazear 

one thing we were struggling with when comparing with other search engines is to define/report the precursor charge range that is searched by sage.

I saw this:
https://github.com/lazear/sage/blob/master/crates/sage/src/scoring.rs#L301

So I assume it is hard-coded to 2-5.

For everything I did so far this would be fine, so I do not necessarily need to specify it (although others might).
Anyway, my main concern is that I did not find this in the documentation. If I missed something, please close, otherwise it would be nice to find it somewhere outside of the code. If you tell me where, I can also add a sentence but you will know the internals better.

Thanks!!

**Comment by lazear** [comment]
Thanks for the catch - I will update the docs accordingly. I can also add it as a configuration option for the next release!

**Comment by lazear** [comment]
I have updated the docs, and added a `"precursor_charge": [2, 4]` option to the configuration file as well.
