### ISSUE TITLE
System cannot find raw file

### ISSUE THREAD

**Issue by ht-lau** [lazear/sage#9]
Hello Michael,

I ran into a problem in that the raw file cannot be read. I am using Windows 10.

In CMD I have 

- cd into the sage folder
- moved the followings into the sage folder: my.fasta, test.json, LQSRPAAPPAPGPGQLTLR.mzML

test.json:
    {
      "database": {
        "bucket_size": 8192,
        "fragment_min_mz": 135.0,
        "fragment_max_mz": 1350.0,
        "peptide_min_len": 6,
        "peptide_max_len": 65,
        "missed_cleavages": 2,
        "static_mods": {
          "C": 57.0215
        },
        "decoy_prefix": "rev_",
        "fasta": "my.fasta"
      },
      "precursor_tol": {
        "ppm": [-10,10] 
      },
      "fragment_tol": {
        "ppm": [-20.0, 20.0]
      },
      "isotope_errors": [-1, 3],
       "deisotope": true,
      "chimera": true,
      "output_directory": "output",
      "max_fragment_charge": 2,
      "process_files_parallel": true,
      "mzml_paths": ["LQSRPAAPPAPGPGQLTLR.mzML"]
     }

I keep running into the following error

    Finished release [optimized] target(s) in 0.12s
     Running `target\release\sage.exe test.json`
    [2022-09-06T20:50:54Z INFO  sage] generated 96410556 fragments in 12554ms
    [2022-09-06T20:50:54Z WARN  sage] linear model fitting failed, falling back to poisson-based FDR calculation
    Encountered error while processing LQSRPAAPPAPGPGQLTLR.mzML: The system cannot find the path specified. (os error 3)

Where should I keep the .mzML? I have also tried to put the full path (["C:/Users/user/sage/LQSRPAAPPAPGPGQLTLR.mzML"] to the .json, but still getting the same error. 

Thanks
HT

**Comment by lazear** [comment]
Hi  HT,

Thanks for trying out Sage - it's trying to write a file to `output/LQSRPAAPPAPGPGQLTLR.sage.pin` - and that folder likely doesn't exist... This is a particularly bad error message, thanks for making the issue!
