### ISSUE TITLE
Restrict enzyme in multiple AA

### ISSUE THREAD

**Issue by ypriverol** [lazear/sage#90]
@lazear How can you define in the restrict field when you need to define multiple AA. This is about the discussion in quantms https://github.com/bigbio/quantms/issues/296. 
Thanks in advance.

**Comment by jpfeuffer** [comment]
And could you clarify how one would specify no restrictions?
In the linked issue we tried `restrict: ""` and this seems to not have been accepted at all.

Thanks! 🙏

**Comment by lazear** [comment]
I'm on vacation for the next 10 days or so -

Here is an example of Trypsin: https://sage-docs.vercel.app/docs/configuration/example_PXD001468

Trypsin/P would set restrict to `null`. The type of the `restrict` is `Option<char>`, so you cannot pass multiple characters or the empty string. The default value is `null` (no restrict).

**Comment by lazear** [comment]
Is there a case where multiple amino acids are necessary for restriction? If no such enzymes exist, I think we can probably leave as-is, right?
