### ISSUE TITLE
Single charged precursors?

### ISSUE THREAD

**Issue by patrick-willems** [lazear/sage#95]
First of all, thanks for the great tool - I am a large fan of this tool.

In some tests I ran, I noticed that single charged precursors are not picked up in the results. I tested this on a mzML input where many (> 1000) 1+ peptide precursors were identified by Comet and MSFragger, though only 2+/3+ precursors by Sage. Is there some setting that  has to be adapted still?

Thanks!
Patrick

**Comment by lazear** [comment]
Hi Patrick,

Can you try changing the [`precursor_charge`](https://sage-docs.vercel.app/docs/configuration/tolerance#precursor-charge-range) configuration option to something like `[1, 4]`? If that fails, can you share your configuration file, output logs, and mzML file?

**Comment by patrick-willems** [comment]
Hey,

Yes that was the case, I even tried with [0,4]. I will send you a PM with the mzML, config, FASTA etc. 

Thanks!
